name: C Program Build, Format & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc valgrind clang-format doxygen

      - name: Check C Code Formatting
        run: |
          for file in src/*.c; do
            if [ -f "$file" ]; then
              clang-format --dry-run --Werror $file || echo "Formatting issue detected in $file!"
            fi
          done

      - name: Compile C Programs
        run: |
          for file in src/*.c; do
            gcc -Wall -Wextra -o ${file%.c} $file || exit 1
          done

      - name: Run Memory Leak Check with Valgrind (excluding shared memory programs)
        run: |
          for file in src/*.c; do
            output=${file%.c}
            if [ -f "$output" ] && [[ "$output" != "src/exp4_shr_writer" ]] && [[ "$output" != "src/exp4_shr_reader" ]]  && [[ "$output" != "src/exp6*" ]]  ; then
              valgrind --leak-check=full --error-exitcode=1 ./$output || exit 1
            fi
          done

      - name: Run additonal cheaks
        run: valgrind --leak-check=full --error-exitcode=1 ./scripts/checks.sh




